name: Run IRIS Analysis

permissions:
  id-token: write
  contents: read
  pull-requests: read
  statuses: read
  checks: read

on:
  schedule:
    # At 03:00 UTC every day
    - cron: '0 3 * * *'

jobs:
  run-iris:
    runs-on: github-ubuntu-latest-s
    steps:
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "SonarSource_go"
          primary_platform: "Next"
          shadow1_project_key: "SonarSource_go"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "SonarSource_go"
          shadow2_platform: "SQC-US"
